env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
  # tscでチェックするので無効
  import/no-unresolved:
    - off
  import/no-commonjs:
    - warn
  import/newline-after-import:
    - warn
  import/order:
    - warn
    - alphabetize:
        order: asc
      pathGroups:
        - pattern: react
          group: builtin
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      warnOnUnassignedImports: true
