name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install main
        run: npm --production=false install
      - name: Install build-page-tools
        working-directory: build-page-tools
        run: npm --production=false install
      - name: Lint
        run: npm run lint
